#version 460

#extension GL_ARB_gpu_shader_int64: enable

layout(local_size_x = 64) in;

struct Draw_Elements_Indirect_Command {
    uint count;
    uint instance_count;
    uint first_index;
    int	 base_vertex;
    uint base_instance;
};

struct GPU_Entity { // todo can maybe just be pos
    mat4 transform;
    uint is_dirty;
    uint animation_command_index;
    uint padding[2];
};

struct GPU_Mesh {
    mat4 transform;
    int base_vertex;
    uint vertex_count;
    uint base_index;
    uint index_count;
    vec4 bounding_sphere; // maybe use transform for some
    uint entity_index;
    uint skinned_to_static_offset; // offset from  
    // could add needs skin flag?
    uint padding[2];
};

struct Per_Object_Data {
    mat4 model_matrix;
    mat4 normal_matrix;
    vec4 base_color;
    vec4 emissive_factor;
    
    uint64_t albedo;
    uint64_t normal;
    uint64_t met_rough;
    uint64_t emissive;
    uint64_t amb_occ;
    uint64_t padding;

    float alpha_cutoff;
    float metallic_factor; // 4
    float roughness_factor; // 4
    uint bone_offset; // todo remove
};

layout(std430, binding = 0) buffer Draw_Commands {
    Draw_Elements_Indirect_Command draw_commands[];
};

layout(std430, binding = 1) buffer Draw_Command_Count {
    uint draw_count;
    uint csm_draw_count;
};

layout(std430, binding = 2) buffer Entities {
    GPU_Entity entities[];
};

layout(std430, binding = 3) buffer Meshes {
    GPU_Mesh meshes[];
};

layout(std430, binding = 4) buffer Per_Mesh_Data {
    Per_Object_Data per_mesh_data[];
};

layout(std430, binding = 5) buffer CSM_Draw_Commands {
    Draw_Elements_Indirect_Command csm_draw_commands[];
};

uniform uint num_meshes;
uniform mat4 view;
uniform float frustum[4];
//float znear = -.5;
//float zfar = 10000;
uniform bool infinite_far;
// frustum stuff
// max meshes

bool visible(uint index) {
	//grab sphere cull data from the object buffer
	vec4 sphereBounds = meshes[index].bounding_sphere;

	vec3 center = sphereBounds.xyz;
	center += entities[meshes[index].entity_index].transform[3].xyz;

	center = (view * vec4(center,1.f)).xyz;
	float radius = sphereBounds.w;

	bool visible = true;

	// the left/top/right/bottom plane culling utilizes frustum symmetry to cull against two planes at the same time
	visible = visible && center.z * frustum[1] - abs(center.x) * frustum[0] > -radius;
	visible = visible && center.z * frustum[3] - abs(center.y) * frustum[2] > -radius;
	// the near/far plane culling uses camera space Z directly
    visible = visible && -center.z + radius > .1 && -center.z - radius < 1000;
	// visible = visible; // || cullData.cullingEnabled == 0;
	return visible;
}

void main() {
	uint gID = gl_GlobalInvocationID.x;

	if(gID < num_meshes) {
    
        GPU_Mesh mesh = meshes[gID];
        uint entity_idx = meshes[gID].entity_index;
        
        if (entities[entity_idx].is_dirty != 0) {
            mat4 model_matrix = entities[entity_idx].transform * mesh.transform;
            per_mesh_data[gID].model_matrix = model_matrix;

            // check non uniform 
            // if needs normal mat
            mat3 upper3x3 = mat3(model_matrix);
            mat3 normal_mat3 = transpose(inverse(upper3x3));
            per_mesh_data[gID].normal_matrix = mat4(normal_mat3);
            // else
            // normal <- model

            per_mesh_data[gID].emissive_factor = vec4(4.0);
        } else {
            per_mesh_data[gID].emissive_factor = vec4(0.0);
        }

        // cull view frustum if has flag
        // todo could maybe do lod-ing?
		if(visible(gID)) {
			uint index = atomicAdd(draw_count, 1);

            Draw_Elements_Indirect_Command draw_command;
            draw_command.count = mesh.index_count;
            draw_command.instance_count = 1;
            draw_command.first_index = mesh.base_index;
            draw_command.base_vertex = mesh.base_vertex;
            draw_command.base_instance = gID;
        
            draw_commands[index] = draw_command;

        }

        // cull animated against frustum if has flag
            // submit animation command (if gpu animation)
            // submit draw command
        
        // cull CSM frustums if has flag
        if (true) {
            uint index = atomicAdd(csm_draw_count, 1);

            Draw_Elements_Indirect_Command draw_command;
            draw_command.count = mesh.index_count;
            draw_command.instance_count = 1;
            draw_command.first_index = mesh.base_index;
            draw_command.base_vertex = mesh.base_vertex;
            draw_command.base_instance = gID;
        
            csm_draw_commands[index] = draw_command;
        }
	}
}
